### ISSUE TITLE
Не работает Spotify интеграция в README.md

### ISSUE THREAD

**Issue by Frestein** [KanaMonogatari/KanaMonogatari#1]
Пофикси, а лучше удали вовсе, гений.

**Comment by KanaMonogatari** [comment]
Иди работай.

**Comment by Frestein** [comment]
Прости, что у моих родителей не нашлось лишнего миллиона, чтобы отправить меня в другую страну работать посудомойкой((9

**Comment by KanaMonogatari** [comment]
Не извиняю.
